[package]
name = "akkadia-vfs"
version = "0.4.3"
authors = ["Nick Cameron <ncameron@mozilla.com>"]
description = "Virtual File System for the RLS"
license = "Apache-2.0/MIT"
repository = "https://github.com/nrc/rls-vfs"
categories = ["development-tools"]

[dependencies]
racer = { version = "2.0", optional = true }

[dependencies.akkadia-span]
path = "../akkadia-span"

[features]
racer-impls = ["racer"]